package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/CodeWarrior-debug/perspectize/backend/internal/adapters/auth"
	"github.com/CodeWarrior-debug/perspectize/backend/internal/adapters/graphql/model"
	"github.com/CodeWarrior-debug/perspectize/backend/internal/core/domain"
)

// AssistantReply is the resolver for the assistantReply field.
func (r *subscriptionResolver) AssistantReply(ctx context.Context, input model.AssistantAskInput) (<-chan model.AssistantEvent, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	if r.Assistant == nil {
		return nil, domain.ErrAssistantDisabled
	}
	page := ""
	if input.Page != nil {
		page = *input.Page
	}

	events, err := r.Assistant.Ask(ctx, actor.ID, input.Message, page)
	if err != nil {
		return nil, err
	}

	out := make(chan model.AssistantEvent, subscriptionBuffer)
	go func() {
		defer close(out)
		for e := range events {
			select {
			case out <- assistantEventToModel(e):
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}
