"""Regenerate src/thumbs.ts: small inline JPEGs for sample-row thumbnails.

The preview must render thumbnails without fetching remote images: a
claude.ai artifact's CSP blocks every external image host, and file:// opens
should not depend on the network either. Each entry maps the image URL a
sample row names (the real source the app would load) to a ~240px data URI.

    pip install pillow
    python3 scripts/build_thumbs.py
"""
import base64, io, json, pathlib, re, urllib.request
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = (ROOT / 'src' / 'catalog.ts').read_text()
URLS = sorted(set(re.findall(r"img: '([^']+)'", CATALOG)))

out = {}
for url in URLS:
    req = urllib.request.Request(url, headers={'User-Agent': 'perspectize-content-type-designer/1.0'})
    img = Image.open(io.BytesIO(urllib.request.urlopen(req, timeout=60).read())).convert('RGB')
    img.thumbnail((240, 240))
    buf = io.BytesIO()
    img.save(buf, 'JPEG', quality=78, optimize=True)
    out[url] = 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode()
    print(f'{len(buf.getvalue()):>7} B  {img.size}  {url}')

body = ',\n'.join(f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in out.items())
(ROOT / 'src' / 'thumbs.ts').write_text(
    '// GENERATED by scripts/build_thumbs.py — do not edit by hand.\n'
    '// Sample-row image URL -> ~240px inline JPEG, so the preview renders\n'
    '// thumbnails with no network access (artifact CSP, file:// opens).\n'
    f'export const THUMBS: Record<string, string> = {{\n{body}\n}};\n'
)
